apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9090
    targetPort: http
  selector:
    app: prometheus
    prometheus: k8s
  type: NodePort
